### ISSUE TITLE
Image size (84x84) for ResNet12 & WRN-28-10 lead to few LRs

### ISSUE THREAD

**Issue by yohann84L** [chenhaoxing/MATANet#2]
Hello, 
You did not specify in the paper if you use the same image size for Conv_64F (`84x84`) and for ResNet12/WRN-28-10. 
Indeed, for ResNet12 and image size `84x84` the penultimate conv layer is size `512x3x3` which mean 9 LRs and that seams very low compared to the 441 LRs of Conv_64F. However you get better results on miniImageNet with those 2 deeper network.

Am I missing something ? Did you use other layer than the last one ? Or bigger image ?

Thanks!

**Comment by chenhaoxing** [comment]
Thanks for your question. For ResNet-12, we only add a max-pooling layer in the first two ResBlock, similar treatment for WRN. In addition, you can refer to [DN4](https://github.com/WenbinLee/DN4).

**Comment by chenhaoxing** [comment]
> Hello,
> You did not specify in the paper if you use the same image size for Conv_64F (`84x84`) and for ResNet12/WRN-28-10.
> Indeed, for ResNet12 and image size `84x84` the penultimate conv layer is size `512x3x3` which mean 9 LRs and that seams very low compared to the 441 LRs of Conv_64F. However you get better results on miniImageNet with those 2 deeper network.
> 
> Am I missing something ? Did you use other layer than the last one ? Or bigger image ?
> 
> Thanks!

Thanks for your question. For ResNet-12, we only add a max-pooling layer in the first two ResBlock, similar treatment for WRN. In addition, you can refer [DN4](https://github.com/WenbinLee/DN4).

**Comment by yohann84L** [comment]
Okay great ! Thank you for your answer 🙂
