### ISSUE TITLE
I don't find the definition of Imagefolder_csv

### ISSUE THREAD

**Issue by tangxinvc** [chenhaoxing/MATANet#4]

**Comment by RitchieAlpha** [comment]
Same question！ @chenhaoxing

**Comment by chenhaoxing** [comment]
> Same question！ @chenhaoxing

Sorry, because time has passed for a long time, uploading file error, now upload, you can try again. Also, using my latest "ssformers" repo is highly recommended. Few-shot learning experiments require pre-trained ResNet-12.

**Comment by chenhaoxing** [comment]
> No description provided.

Sorry, because time has passed for a long time, uploading file error, now upload, you can try again. Also, using my latest "ssformers" repo is highly recommended. Few-shot learning experiments require pre-trained ResNet-12.
